// Code generated by go generate; DO NOT EDIT.

package packets

// Packet IDs for configuration phase (serverbound)
const (
	C2SClientInformationConfigurationID = 0
	C2SCookieResponseConfigurationID = 1
	C2SCustomPayloadConfigurationID = 2
	C2SFinishConfigurationID = 3
	C2SKeepAliveConfigurationID = 4
	C2SPongConfigurationID = 5
	C2SResourcePackConfigurationID = 6
	C2SSelectKnownPacksID = 7
	C2SCustomClickActionConfigurationID = 8
	C2SAcceptCodeOfConductID = 9
)
