// Code generated by go generate; DO NOT EDIT.

package packets

// Packet IDs for play phase (serverbound)
const (
	C2SAcceptTeleportationID       int32 = 0
	C2SBlockEntityTagQueryID       int32 = 1
	C2SBundleItemSelectedID        int32 = 2
	C2SChangeDifficultyID          int32 = 3
	C2SChangeGameModeID            int32 = 4
	C2SChatAckID                   int32 = 5
	C2SChatCommandID               int32 = 6
	C2SChatCommandSignedID         int32 = 7
	C2SChatID                      int32 = 8
	C2SChatSessionUpdateID         int32 = 9
	C2SChunkBatchReceivedID        int32 = 10
	C2SClientCommandID             int32 = 11
	C2SClientTickEndID             int32 = 12
	C2SClientInformationPlayID     int32 = 13
	C2SCommandSuggestionID         int32 = 14
	C2SConfigurationAcknowledgedID int32 = 15
	C2SContainerButtonClickID      int32 = 16
	C2SContainerClickID            int32 = 17
	C2SContainerCloseID            int32 = 18
	C2SContainerSlotStateChangedID int32 = 19
	C2SCookieResponsePlayID        int32 = 20
	C2SCustomPayloadPlayID         int32 = 21
	C2SDebugSubscriptionRequestID  int32 = 22
	C2SEditBookID                  int32 = 23
	C2SEntityTagQueryID            int32 = 24
	C2SInteractID                  int32 = 25
	C2SJigsawGenerateID            int32 = 26
	C2SKeepAlivePlayID             int32 = 27
	C2SLockDifficultyID            int32 = 28
	C2SMovePlayerPosID             int32 = 29
	C2SMovePlayerPosRotID          int32 = 30
	C2SMovePlayerRotID             int32 = 31
	C2SMovePlayerStatusOnlyID      int32 = 32
	C2SMoveVehicleID               int32 = 33
	C2SPaddleBoatID                int32 = 34
	C2SPickItemFromBlockID         int32 = 35
	C2SPickItemFromEntityID        int32 = 36
	C2SPingRequestPlayID           int32 = 37
	C2SPlaceRecipeID               int32 = 38
	C2SPlayerAbilitiesID           int32 = 39
	C2SPlayerActionID              int32 = 40
	C2SPlayerCommandID             int32 = 41
	C2SPlayerInputID               int32 = 42
	C2SPlayerLoadedID              int32 = 43
	C2SPongPlayID                  int32 = 44
	C2SRecipeBookChangeSettingsID  int32 = 45
	C2SRecipeBookSeenRecipeID      int32 = 46
	C2SRenameItemID                int32 = 47
	C2SResourcePackPlayID          int32 = 48
	C2SSeenAdvancementsID          int32 = 49
	C2SSelectTradeID               int32 = 50
	C2SSetBeaconID                 int32 = 51
	C2SSetCarriedItemID            int32 = 52
	C2SSetCommandBlockID           int32 = 53
	C2SSetCommandMinecartID        int32 = 54
	C2SSetCreativeModeSlotID       int32 = 55
	C2SSetJigsawBlockID            int32 = 56
	C2SSetStructureBlockID         int32 = 57
	C2SSetTestBlockID              int32 = 58
	C2SSignUpdateID                int32 = 59
	C2SSwingID                     int32 = 60
	C2STeleportToEntityID          int32 = 61
	C2STestInstanceBlockActionID   int32 = 62
	C2SUseItemOnID                 int32 = 63
	C2SUseItemID                   int32 = 64
	C2SCustomClickActionPlayID     int32 = 65
)
