// Code generated by go generate; DO NOT EDIT.

package packets

// Packet IDs for configuration phase (serverbound)
const (
	C2SClientInformationConfigurationID int32 = 0
	C2SCookieResponseConfigurationID    int32 = 1
	C2SCustomPayloadConfigurationID     int32 = 2
	C2SFinishConfigurationID            int32 = 3
	C2SKeepAliveConfigurationID         int32 = 4
	C2SPongConfigurationID              int32 = 5
	C2SResourcePackConfigurationID      int32 = 6
	C2SSelectKnownPacksID               int32 = 7
	C2SCustomClickActionConfigurationID int32 = 8
	C2SAcceptCodeOfConductID            int32 = 9
)
