// Code generated by go generate; DO NOT EDIT.

package packets

// Packet IDs for login phase (serverbound)
const (
	C2SHelloID = 0
	C2SKeyID = 1
	C2SCustomQueryAnswerID = 2
	C2SLoginAcknowledgedID = 3
	C2SCookieResponseLoginID = 4
)
