// Code generated by go generate; DO NOT EDIT.

package packets

// Packet IDs for login phase (clientbound)
const (
	S2CLoginDisconnectID = 0
	S2CHelloID = 1
	S2CLoginFinishedID = 2
	S2CLoginCompressionID = 3
	S2CCustomQueryID = 4
	S2CCookieRequestLoginID = 5
)
