// Code generated by go generate; DO NOT EDIT.

package entities

// Entity type protocol IDs
const (
	AcaciaBoat           int32 = 0
	AcaciaChestBoat      int32 = 1
	Allay                int32 = 2
	AreaEffectCloud      int32 = 3
	Armadillo            int32 = 4
	ArmorStand           int32 = 5
	Arrow                int32 = 6
	Axolotl              int32 = 7
	BambooChestRaft      int32 = 8
	BambooRaft           int32 = 9
	Bat                  int32 = 10
	Bee                  int32 = 11
	BirchBoat            int32 = 12
	BirchChestBoat       int32 = 13
	Blaze                int32 = 14
	BlockDisplay         int32 = 15
	Bogged               int32 = 16
	Breeze               int32 = 17
	BreezeWindCharge     int32 = 18
	Camel                int32 = 19
	CamelHusk            int32 = 20
	Cat                  int32 = 21
	CaveSpider           int32 = 22
	CherryBoat           int32 = 23
	CherryChestBoat      int32 = 24
	ChestMinecart        int32 = 25
	Chicken              int32 = 26
	Cod                  int32 = 27
	CommandBlockMinecart int32 = 29
	CopperGolem          int32 = 28
	Cow                  int32 = 30
	Creaking             int32 = 31
	Creeper              int32 = 32
	DarkOakBoat          int32 = 33
	DarkOakChestBoat     int32 = 34
	Dolphin              int32 = 35
	Donkey               int32 = 36
	DragonFireball       int32 = 37
	Drowned              int32 = 38
	Egg                  int32 = 39
	ElderGuardian        int32 = 40
	EndCrystal           int32 = 45
	EnderDragon          int32 = 43
	EnderPearl           int32 = 44
	Enderman             int32 = 41
	Endermite            int32 = 42
	Evoker               int32 = 46
	EvokerFangs          int32 = 47
	ExperienceBottle     int32 = 48
	ExperienceOrb        int32 = 49
	EyeOfEnder           int32 = 50
	FallingBlock         int32 = 51
	Fireball             int32 = 52
	FireworkRocket       int32 = 53
	FishingBobber        int32 = 156
	Fox                  int32 = 54
	Frog                 int32 = 55
	FurnaceMinecart      int32 = 56
	Ghast                int32 = 57
	Giant                int32 = 59
	GlowItemFrame        int32 = 60
	GlowSquid            int32 = 61
	Goat                 int32 = 62
	Guardian             int32 = 63
	HappyGhast           int32 = 58
	Hoglin               int32 = 64
	HopperMinecart       int32 = 65
	Horse                int32 = 66
	Husk                 int32 = 67
	Illusioner           int32 = 68
	Interaction          int32 = 69
	IronGolem            int32 = 70
	Item                 int32 = 71
	ItemDisplay          int32 = 72
	ItemFrame            int32 = 73
	JungleBoat           int32 = 74
	JungleChestBoat      int32 = 75
	LeashKnot            int32 = 76
	LightningBolt        int32 = 77
	LingeringPotion      int32 = 106
	Llama                int32 = 78
	LlamaSpit            int32 = 79
	MagmaCube            int32 = 80
	MangroveBoat         int32 = 81
	MangroveChestBoat    int32 = 82
	Mannequin            int32 = 83
	Marker               int32 = 84
	Minecart             int32 = 85
	Mooshroom            int32 = 86
	Mule                 int32 = 87
	Nautilus             int32 = 88
	OakBoat              int32 = 89
	OakChestBoat         int32 = 90
	Ocelot               int32 = 91
	OminousItemSpawner   int32 = 92
	Painting             int32 = 93
	PaleOakBoat          int32 = 94
	PaleOakChestBoat     int32 = 95
	Panda                int32 = 96
	Parched              int32 = 97
	Parrot               int32 = 98
	Phantom              int32 = 99
	Pig                  int32 = 100
	Piglin               int32 = 101
	PiglinBrute          int32 = 102
	Pillager             int32 = 103
	Player               int32 = 155
	PolarBear            int32 = 104
	Pufferfish           int32 = 107
	Rabbit               int32 = 108
	Ravager              int32 = 109
	Salmon               int32 = 110
	Sheep                int32 = 111
	Shulker              int32 = 112
	ShulkerBullet        int32 = 113
	Silverfish           int32 = 114
	Skeleton             int32 = 115
	SkeletonHorse        int32 = 116
	Slime                int32 = 117
	SmallFireball        int32 = 118
	Sniffer              int32 = 119
	SnowGolem            int32 = 121
	Snowball             int32 = 120
	SpawnerMinecart      int32 = 122
	SpectralArrow        int32 = 123
	Spider               int32 = 124
	SplashPotion         int32 = 105
	SpruceBoat           int32 = 125
	SpruceChestBoat      int32 = 126
	Squid                int32 = 127
	Stray                int32 = 128
	Strider              int32 = 129
	Tadpole              int32 = 130
	TextDisplay          int32 = 131
	Tnt                  int32 = 132
	TntMinecart          int32 = 133
	TraderLlama          int32 = 134
	Trident              int32 = 135
	TropicalFish         int32 = 136
	Turtle               int32 = 137
	Vex                  int32 = 138
	Villager             int32 = 139
	Vindicator           int32 = 140
	WanderingTrader      int32 = 141
	Warden               int32 = 142
	WindCharge           int32 = 143
	Witch                int32 = 144
	Wither               int32 = 145
	WitherSkeleton       int32 = 146
	WitherSkull          int32 = 147
	Wolf                 int32 = 148
	Zoglin               int32 = 149
	Zombie               int32 = 150
	ZombieHorse          int32 = 151
	ZombieNautilus       int32 = 152
	ZombieVillager       int32 = 153
	ZombifiedPiglin      int32 = 154
)

var entityByName = map[string]int32{
	"minecraft:acacia_boat":            0,
	"minecraft:acacia_chest_boat":      1,
	"minecraft:allay":                  2,
	"minecraft:area_effect_cloud":      3,
	"minecraft:armadillo":              4,
	"minecraft:armor_stand":            5,
	"minecraft:arrow":                  6,
	"minecraft:axolotl":                7,
	"minecraft:bamboo_chest_raft":      8,
	"minecraft:bamboo_raft":            9,
	"minecraft:bat":                    10,
	"minecraft:bee":                    11,
	"minecraft:birch_boat":             12,
	"minecraft:birch_chest_boat":       13,
	"minecraft:blaze":                  14,
	"minecraft:block_display":          15,
	"minecraft:bogged":                 16,
	"minecraft:breeze":                 17,
	"minecraft:breeze_wind_charge":     18,
	"minecraft:camel":                  19,
	"minecraft:camel_husk":             20,
	"minecraft:cat":                    21,
	"minecraft:cave_spider":            22,
	"minecraft:cherry_boat":            23,
	"minecraft:cherry_chest_boat":      24,
	"minecraft:chest_minecart":         25,
	"minecraft:chicken":                26,
	"minecraft:cod":                    27,
	"minecraft:command_block_minecart": 29,
	"minecraft:copper_golem":           28,
	"minecraft:cow":                    30,
	"minecraft:creaking":               31,
	"minecraft:creeper":                32,
	"minecraft:dark_oak_boat":          33,
	"minecraft:dark_oak_chest_boat":    34,
	"minecraft:dolphin":                35,
	"minecraft:donkey":                 36,
	"minecraft:dragon_fireball":        37,
	"minecraft:drowned":                38,
	"minecraft:egg":                    39,
	"minecraft:elder_guardian":         40,
	"minecraft:end_crystal":            45,
	"minecraft:ender_dragon":           43,
	"minecraft:ender_pearl":            44,
	"minecraft:enderman":               41,
	"minecraft:endermite":              42,
	"minecraft:evoker":                 46,
	"minecraft:evoker_fangs":           47,
	"minecraft:experience_bottle":      48,
	"minecraft:experience_orb":         49,
	"minecraft:eye_of_ender":           50,
	"minecraft:falling_block":          51,
	"minecraft:fireball":               52,
	"minecraft:firework_rocket":        53,
	"minecraft:fishing_bobber":         156,
	"minecraft:fox":                    54,
	"minecraft:frog":                   55,
	"minecraft:furnace_minecart":       56,
	"minecraft:ghast":                  57,
	"minecraft:giant":                  59,
	"minecraft:glow_item_frame":        60,
	"minecraft:glow_squid":             61,
	"minecraft:goat":                   62,
	"minecraft:guardian":               63,
	"minecraft:happy_ghast":            58,
	"minecraft:hoglin":                 64,
	"minecraft:hopper_minecart":        65,
	"minecraft:horse":                  66,
	"minecraft:husk":                   67,
	"minecraft:illusioner":             68,
	"minecraft:interaction":            69,
	"minecraft:iron_golem":             70,
	"minecraft:item":                   71,
	"minecraft:item_display":           72,
	"minecraft:item_frame":             73,
	"minecraft:jungle_boat":            74,
	"minecraft:jungle_chest_boat":      75,
	"minecraft:leash_knot":             76,
	"minecraft:lightning_bolt":         77,
	"minecraft:lingering_potion":       106,
	"minecraft:llama":                  78,
	"minecraft:llama_spit":             79,
	"minecraft:magma_cube":             80,
	"minecraft:mangrove_boat":          81,
	"minecraft:mangrove_chest_boat":    82,
	"minecraft:mannequin":              83,
	"minecraft:marker":                 84,
	"minecraft:minecart":               85,
	"minecraft:mooshroom":              86,
	"minecraft:mule":                   87,
	"minecraft:nautilus":               88,
	"minecraft:oak_boat":               89,
	"minecraft:oak_chest_boat":         90,
	"minecraft:ocelot":                 91,
	"minecraft:ominous_item_spawner":   92,
	"minecraft:painting":               93,
	"minecraft:pale_oak_boat":          94,
	"minecraft:pale_oak_chest_boat":    95,
	"minecraft:panda":                  96,
	"minecraft:parched":                97,
	"minecraft:parrot":                 98,
	"minecraft:phantom":                99,
	"minecraft:pig":                    100,
	"minecraft:piglin":                 101,
	"minecraft:piglin_brute":           102,
	"minecraft:pillager":               103,
	"minecraft:player":                 155,
	"minecraft:polar_bear":             104,
	"minecraft:pufferfish":             107,
	"minecraft:rabbit":                 108,
	"minecraft:ravager":                109,
	"minecraft:salmon":                 110,
	"minecraft:sheep":                  111,
	"minecraft:shulker":                112,
	"minecraft:shulker_bullet":         113,
	"minecraft:silverfish":             114,
	"minecraft:skeleton":               115,
	"minecraft:skeleton_horse":         116,
	"minecraft:slime":                  117,
	"minecraft:small_fireball":         118,
	"minecraft:sniffer":                119,
	"minecraft:snow_golem":             121,
	"minecraft:snowball":               120,
	"minecraft:spawner_minecart":       122,
	"minecraft:spectral_arrow":         123,
	"minecraft:spider":                 124,
	"minecraft:splash_potion":          105,
	"minecraft:spruce_boat":            125,
	"minecraft:spruce_chest_boat":      126,
	"minecraft:squid":                  127,
	"minecraft:stray":                  128,
	"minecraft:strider":                129,
	"minecraft:tadpole":                130,
	"minecraft:text_display":           131,
	"minecraft:tnt":                    132,
	"minecraft:tnt_minecart":           133,
	"minecraft:trader_llama":           134,
	"minecraft:trident":                135,
	"minecraft:tropical_fish":          136,
	"minecraft:turtle":                 137,
	"minecraft:vex":                    138,
	"minecraft:villager":               139,
	"minecraft:vindicator":             140,
	"minecraft:wandering_trader":       141,
	"minecraft:warden":                 142,
	"minecraft:wind_charge":            143,
	"minecraft:witch":                  144,
	"minecraft:wither":                 145,
	"minecraft:wither_skeleton":        146,
	"minecraft:wither_skull":           147,
	"minecraft:wolf":                   148,
	"minecraft:zoglin":                 149,
	"minecraft:zombie":                 150,
	"minecraft:zombie_horse":           151,
	"minecraft:zombie_nautilus":        152,
	"minecraft:zombie_villager":        153,
	"minecraft:zombified_piglin":       154,
}

var entityByID = map[int32]string{
	0:   "minecraft:acacia_boat",
	1:   "minecraft:acacia_chest_boat",
	2:   "minecraft:allay",
	3:   "minecraft:area_effect_cloud",
	4:   "minecraft:armadillo",
	5:   "minecraft:armor_stand",
	6:   "minecraft:arrow",
	7:   "minecraft:axolotl",
	8:   "minecraft:bamboo_chest_raft",
	9:   "minecraft:bamboo_raft",
	10:  "minecraft:bat",
	11:  "minecraft:bee",
	12:  "minecraft:birch_boat",
	13:  "minecraft:birch_chest_boat",
	14:  "minecraft:blaze",
	15:  "minecraft:block_display",
	16:  "minecraft:bogged",
	17:  "minecraft:breeze",
	18:  "minecraft:breeze_wind_charge",
	19:  "minecraft:camel",
	20:  "minecraft:camel_husk",
	21:  "minecraft:cat",
	22:  "minecraft:cave_spider",
	23:  "minecraft:cherry_boat",
	24:  "minecraft:cherry_chest_boat",
	25:  "minecraft:chest_minecart",
	26:  "minecraft:chicken",
	27:  "minecraft:cod",
	29:  "minecraft:command_block_minecart",
	28:  "minecraft:copper_golem",
	30:  "minecraft:cow",
	31:  "minecraft:creaking",
	32:  "minecraft:creeper",
	33:  "minecraft:dark_oak_boat",
	34:  "minecraft:dark_oak_chest_boat",
	35:  "minecraft:dolphin",
	36:  "minecraft:donkey",
	37:  "minecraft:dragon_fireball",
	38:  "minecraft:drowned",
	39:  "minecraft:egg",
	40:  "minecraft:elder_guardian",
	45:  "minecraft:end_crystal",
	43:  "minecraft:ender_dragon",
	44:  "minecraft:ender_pearl",
	41:  "minecraft:enderman",
	42:  "minecraft:endermite",
	46:  "minecraft:evoker",
	47:  "minecraft:evoker_fangs",
	48:  "minecraft:experience_bottle",
	49:  "minecraft:experience_orb",
	50:  "minecraft:eye_of_ender",
	51:  "minecraft:falling_block",
	52:  "minecraft:fireball",
	53:  "minecraft:firework_rocket",
	156: "minecraft:fishing_bobber",
	54:  "minecraft:fox",
	55:  "minecraft:frog",
	56:  "minecraft:furnace_minecart",
	57:  "minecraft:ghast",
	59:  "minecraft:giant",
	60:  "minecraft:glow_item_frame",
	61:  "minecraft:glow_squid",
	62:  "minecraft:goat",
	63:  "minecraft:guardian",
	58:  "minecraft:happy_ghast",
	64:  "minecraft:hoglin",
	65:  "minecraft:hopper_minecart",
	66:  "minecraft:horse",
	67:  "minecraft:husk",
	68:  "minecraft:illusioner",
	69:  "minecraft:interaction",
	70:  "minecraft:iron_golem",
	71:  "minecraft:item",
	72:  "minecraft:item_display",
	73:  "minecraft:item_frame",
	74:  "minecraft:jungle_boat",
	75:  "minecraft:jungle_chest_boat",
	76:  "minecraft:leash_knot",
	77:  "minecraft:lightning_bolt",
	106: "minecraft:lingering_potion",
	78:  "minecraft:llama",
	79:  "minecraft:llama_spit",
	80:  "minecraft:magma_cube",
	81:  "minecraft:mangrove_boat",
	82:  "minecraft:mangrove_chest_boat",
	83:  "minecraft:mannequin",
	84:  "minecraft:marker",
	85:  "minecraft:minecart",
	86:  "minecraft:mooshroom",
	87:  "minecraft:mule",
	88:  "minecraft:nautilus",
	89:  "minecraft:oak_boat",
	90:  "minecraft:oak_chest_boat",
	91:  "minecraft:ocelot",
	92:  "minecraft:ominous_item_spawner",
	93:  "minecraft:painting",
	94:  "minecraft:pale_oak_boat",
	95:  "minecraft:pale_oak_chest_boat",
	96:  "minecraft:panda",
	97:  "minecraft:parched",
	98:  "minecraft:parrot",
	99:  "minecraft:phantom",
	100: "minecraft:pig",
	101: "minecraft:piglin",
	102: "minecraft:piglin_brute",
	103: "minecraft:pillager",
	155: "minecraft:player",
	104: "minecraft:polar_bear",
	107: "minecraft:pufferfish",
	108: "minecraft:rabbit",
	109: "minecraft:ravager",
	110: "minecraft:salmon",
	111: "minecraft:sheep",
	112: "minecraft:shulker",
	113: "minecraft:shulker_bullet",
	114: "minecraft:silverfish",
	115: "minecraft:skeleton",
	116: "minecraft:skeleton_horse",
	117: "minecraft:slime",
	118: "minecraft:small_fireball",
	119: "minecraft:sniffer",
	121: "minecraft:snow_golem",
	120: "minecraft:snowball",
	122: "minecraft:spawner_minecart",
	123: "minecraft:spectral_arrow",
	124: "minecraft:spider",
	105: "minecraft:splash_potion",
	125: "minecraft:spruce_boat",
	126: "minecraft:spruce_chest_boat",
	127: "minecraft:squid",
	128: "minecraft:stray",
	129: "minecraft:strider",
	130: "minecraft:tadpole",
	131: "minecraft:text_display",
	132: "minecraft:tnt",
	133: "minecraft:tnt_minecart",
	134: "minecraft:trader_llama",
	135: "minecraft:trident",
	136: "minecraft:tropical_fish",
	137: "minecraft:turtle",
	138: "minecraft:vex",
	139: "minecraft:villager",
	140: "minecraft:vindicator",
	141: "minecraft:wandering_trader",
	142: "minecraft:warden",
	143: "minecraft:wind_charge",
	144: "minecraft:witch",
	145: "minecraft:wither",
	146: "minecraft:wither_skeleton",
	147: "minecraft:wither_skull",
	148: "minecraft:wolf",
	149: "minecraft:zoglin",
	150: "minecraft:zombie",
	151: "minecraft:zombie_horse",
	152: "minecraft:zombie_nautilus",
	153: "minecraft:zombie_villager",
	154: "minecraft:zombified_piglin",
}
