// Code generated by go generate; DO NOT EDIT.

package items

// Passthrough codec registrations for components we don't fully decode.
// These copy wire format bytes without interpreting them.

func init() {
	// VarInt passthrough
	for _, id := range []int32{
		ComponentBaseColor,
		ComponentMapId,
		ComponentMapPostProcessing,
		ComponentSwingAnimation,
	} {
		registerVarIntPassthrough(id)
	}

	// Bool passthrough
	for _, id := range []int32{
		ComponentEnchantmentGlintOverride,
	} {
		registerBoolPassthrough(id)
	}

	// String passthrough
	for _, id := range []int32{
		ComponentNoteBlockSound,
		ComponentTooltipStyle,
	} {
		registerStringPassthrough(id)
	}

	// Empty passthrough
	for _, id := range []int32{
		ComponentCreativeSlotLock,
		ComponentIntangibleProjectile,
	} {
		registerEmptyPassthrough(id)
	}

	// Int32 passthrough
	for _, id := range []int32{
		ComponentDyedColor,
	} {
		registerInt32Passthrough(id)
	}

	// NBT passthrough
	for _, id := range []int32{
		ComponentBlockEntityData,
		ComponentBucketEntityData,
		ComponentContainerLoot,
		ComponentCustomData,
		ComponentDebugStickState,
		ComponentEntityData,
		ComponentLock,
		ComponentMapDecorations,
	} {
		registerNBTPassthrough(id)
	}

	// HolderSet passthrough
	for _, id := range []int32{
		ComponentDamageResistant,
		ComponentRepairable,
	} {
		registerHolderSetPassthrough(id)
	}

	// SlotList passthrough
	for _, id := range []int32{
		ComponentBundleContents,
		ComponentChargedProjectiles,
		ComponentContainer,
	} {
		registerSlotListPassthrough(id)
	}

	// Slot passthrough
	for _, id := range []int32{
		ComponentUseRemainder,
	} {
		registerSlotPassthrough(id)
	}

	// Entity variant (VarInt) passthrough
	for _, id := range []int32{
		ComponentAxolotlVariant,
		ComponentCatCollar,
		ComponentCatVariant,
		ComponentChickenVariant,
		ComponentCowVariant,
		ComponentFoxVariant,
		ComponentFrogVariant,
		ComponentHorseVariant,
		ComponentLlamaVariant,
		ComponentMooshroomVariant,
		ComponentPaintingVariant,
		ComponentParrotVariant,
		ComponentPigVariant,
		ComponentRabbitVariant,
		ComponentSalmonSize,
		ComponentSheepColor,
		ComponentShulkerColor,
		ComponentTropicalFishBaseColor,
		ComponentTropicalFishPattern,
		ComponentTropicalFishPatternColor,
		ComponentVillagerVariant,
		ComponentWolfCollar,
		ComponentWolfSoundVariant,
		ComponentWolfVariant,
		ComponentZombieNautilusVariant,
	} {
		registerVarIntPassthrough(id)
	}

}
