package main

import (
	"fmt"
	"strings"
)

func generateRegistries(registries map[string]RegistryJSON, outPath string) {
	var sb strings.Builder
	sb.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	sb.WriteString("package registries\n\n")

	// generate registry variables
	sb.WriteString("// Registry instances\nvar (\n")
	for _, name := range sortedKeys(registries) {
		reg := registries[name]
		goName := toGoVarName(name)
		sb.WriteString(fmt.Sprintf("\t%s = newRegistry(%d, %sEntries)\n", goName, reg.ProtocolID, strings.ToLower(goName[:1])+goName[1:]))
	}
	sb.WriteString(")\n\n")

	// generate entry maps
	for _, name := range sortedKeys(registries) {
		reg := registries[name]
		goName := toGoVarName(name)
		varName := strings.ToLower(goName[:1]) + goName[1:] + "Entries"

		sb.WriteString(fmt.Sprintf("var %s = map[string]int32{\n", varName))
		for _, entryName := range sortedKeys(reg.Entries) {
			entry := reg.Entries[entryName]
			sb.WriteString(fmt.Sprintf("\t%q: %d,\n", entryName, entry.ProtocolID))
		}
		sb.WriteString("}\n\n")
	}

	writeFile(outPath, sb.String())
}
