package main

import (
	"fmt"
	"strings"
)

func generateLang(langPath, outPath string) {
	translations := loadJSON[map[string]string](langPath)

	var sb strings.Builder
	sb.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	sb.WriteString("package lang\n\n")

	// generate the map
	sb.WriteString("var translations = map[string]string{\n")
	for _, key := range sortedKeys(translations) {
		value := translations[key]
		sb.WriteString(fmt.Sprintf("\t%q: %q,\n", key, value))
	}
	sb.WriteString("}\n")

	writeFile(outPath, sb.String())
}
