package main

import (
	"fmt"
	"strings"
)

func generateEntities(registries map[string]RegistryJSON, outPath string) {
	entityRegistry := registries["minecraft:entity_type"]

	var sb strings.Builder
	sb.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	sb.WriteString("package entities\n\n")

	// entity type ID constants
	sb.WriteString("// Entity type protocol IDs\nconst (\n")
	for _, name := range sortedKeys(entityRegistry.Entries) {
		entry := entityRegistry.Entries[name]
		goName := toGoVarName(name)
		sb.WriteString(fmt.Sprintf("\t%s = %d\n", goName, entry.ProtocolID))
	}
	sb.WriteString(")\n\n")

	// lookup maps
	sb.WriteString("var entityByName = map[string]int32{\n")
	for _, name := range sortedKeys(entityRegistry.Entries) {
		entry := entityRegistry.Entries[name]
		sb.WriteString(fmt.Sprintf("\t%q: %d,\n", name, entry.ProtocolID))
	}
	sb.WriteString("}\n\n")

	sb.WriteString("var entityByID = map[int32]string{\n")
	for _, name := range sortedKeys(entityRegistry.Entries) {
		entry := entityRegistry.Entries[name]
		sb.WriteString(fmt.Sprintf("\t%d: %q,\n", entry.ProtocolID, name))
	}
	sb.WriteString("}\n")

	writeFile(outPath, sb.String())
}
