package packets

import (
	packets_data "github.com/go-mclib/data/pkg/data/packets"
	jp "github.com/go-mclib/protocol/java_protocol"
)

// PacketFactory creates a new packet instance.
type PacketFactory func() jp.Packet

// PacketRegistries maps phase+bound to a map of packet ID -> factory function.
// Useful for packet-capturing tools like proxy, or tests.
// Keys are in format "phase_bound" like "configuration_c2s" or "play_s2c".
var PacketRegistries = map[string]map[int]PacketFactory{
	"handshake_c2s": {
		int(packets_data.C2SIntentionID): func() jp.Packet { return &C2SIntention{} },
	},
	"status_c2s": {
		int(packets_data.C2SStatusRequestID):     func() jp.Packet { return &C2SStatusRequest{} },
		int(packets_data.C2SPingRequestStatusID): func() jp.Packet { return &C2SPingRequestStatus{} },
	},
	"status_s2c": {
		int(packets_data.S2CStatusResponseID):     func() jp.Packet { return &S2CStatusResponse{} },
		int(packets_data.S2CPongResponseStatusID): func() jp.Packet { return &S2CPongResponseStatus{} },
	},
	"login_c2s": {
		int(packets_data.C2SHelloID):               func() jp.Packet { return &C2SHello{} },
		int(packets_data.C2SKeyID):                 func() jp.Packet { return &C2SKey{} },
		int(packets_data.C2SCustomQueryAnswerID):   func() jp.Packet { return &C2SCustomQueryAnswer{} },
		int(packets_data.C2SLoginAcknowledgedID):   func() jp.Packet { return &C2SLoginAcknowledged{} },
		int(packets_data.C2SCookieResponseLoginID): func() jp.Packet { return &C2SCookieResponseLogin{} },
	},
	"login_s2c": {
		int(packets_data.S2CLoginDisconnectID):    func() jp.Packet { return &S2CLoginDisconnectLogin{} },
		int(packets_data.S2CHelloID):              func() jp.Packet { return &S2CHello{} },
		int(packets_data.S2CLoginFinishedID):      func() jp.Packet { return &S2CLoginFinished{} },
		int(packets_data.S2CLoginCompressionID):   func() jp.Packet { return &S2CLoginCompression{} },
		int(packets_data.S2CCustomQueryID):        func() jp.Packet { return &S2CCustomQuery{} },
		int(packets_data.S2CCookieRequestLoginID): func() jp.Packet { return &S2CCookieRequestLogin{} },
	},
	"configuration_c2s": {
		int(packets_data.C2SClientInformationConfigurationID): func() jp.Packet { return &C2SClientInformationConfiguration{} },
		int(packets_data.C2SCookieResponseConfigurationID):    func() jp.Packet { return &C2SCookieResponseConfiguration{} },
		int(packets_data.C2SCustomPayloadConfigurationID):     func() jp.Packet { return &C2SCustomPayloadConfiguration{} },
		int(packets_data.C2SFinishConfigurationID):            func() jp.Packet { return &C2SFinishConfiguration{} },
		int(packets_data.C2SKeepAliveConfigurationID):         func() jp.Packet { return &C2SKeepAliveConfiguration{} },
		int(packets_data.C2SPongConfigurationID):              func() jp.Packet { return &C2SPongConfiguration{} },
		int(packets_data.C2SResourcePackConfigurationID):      func() jp.Packet { return &C2SResourcePackConfiguration{} },
		int(packets_data.C2SSelectKnownPacksID):               func() jp.Packet { return &C2SSelectKnownPacks{} },
		int(packets_data.C2SCustomClickActionConfigurationID): func() jp.Packet { return &C2SCustomClickActionConfiguration{} },
	},
	"configuration_s2c": {
		int(packets_data.S2CCookieRequestConfigurationID):       func() jp.Packet { return &S2CCookieRequestConfiguration{} },
		int(packets_data.S2CCustomPayloadConfigurationID):       func() jp.Packet { return &S2CCustomPayloadConfiguration{} },
		int(packets_data.S2CDisconnectConfigurationID):          func() jp.Packet { return &S2CDisconnectConfiguration{} },
		int(packets_data.S2CFinishConfigurationID):              func() jp.Packet { return &S2CFinishConfiguration{} },
		int(packets_data.S2CKeepAliveConfigurationID):           func() jp.Packet { return &S2CKeepAliveConfiguration{} },
		int(packets_data.S2CPingConfigurationID):                func() jp.Packet { return &S2CPingConfiguration{} },
		int(packets_data.S2CResetChatID):                        func() jp.Packet { return &S2CResetChat{} },
		int(packets_data.S2CRegistryDataID):                     func() jp.Packet { return &S2CRegistryData{} },
		int(packets_data.S2CResourcePackPopConfigurationID):     func() jp.Packet { return &S2CResourcePackPopConfiguration{} },
		int(packets_data.S2CResourcePackPushConfigurationID):    func() jp.Packet { return &S2CResourcePackPushConfiguration{} },
		int(packets_data.S2CStoreCookieConfigurationID):         func() jp.Packet { return &S2CStoreCookieConfiguration{} },
		int(packets_data.S2CTransferConfigurationID):            func() jp.Packet { return &S2CTransferConfiguration{} },
		int(packets_data.S2CUpdateEnabledFeaturesID):            func() jp.Packet { return &S2CUpdateEnabledFeatures{} },
		int(packets_data.S2CUpdateTagsConfigurationID):          func() jp.Packet { return &S2CUpdateTagsConfiguration{} },
		int(packets_data.S2CSelectKnownPacksID):                 func() jp.Packet { return &S2CSelectKnownPacks{} },
		int(packets_data.S2CCustomReportDetailsConfigurationID): func() jp.Packet { return &S2CCustomReportDetailsConfiguration{} },
		int(packets_data.S2CServerLinksConfigurationID):         func() jp.Packet { return &S2CServerLinksConfiguration{} },
		int(packets_data.S2CClearDialogConfigurationID):         func() jp.Packet { return &S2CClearDialogConfiguration{} },
		int(packets_data.S2CShowDialogConfigurationID):          func() jp.Packet { return &S2CShowDialogConfiguration{} },
		int(packets_data.S2CCodeOfConductID):                    func() jp.Packet { return &S2CCodeOfConduct{} },
	},
	"play_c2s": {
		int(packets_data.C2SAcceptTeleportationID):       func() jp.Packet { return &C2SAcceptTeleportation{} },
		int(packets_data.C2SBlockEntityTagQueryID):       func() jp.Packet { return &C2SBlockEntityTagQuery{} },
		int(packets_data.C2SBundleItemSelectedID):        func() jp.Packet { return &C2SBundleItemSelected{} },
		int(packets_data.C2SChangeDifficultyID):          func() jp.Packet { return &C2SChangeDifficulty{} },
		int(packets_data.C2SChangeGameModeID):            func() jp.Packet { return &C2SChangeGameMode{} },
		int(packets_data.C2SChatAckID):                   func() jp.Packet { return &C2SChatAck{} },
		int(packets_data.C2SChatCommandID):               func() jp.Packet { return &C2SChatCommand{} },
		int(packets_data.C2SChatCommandSignedID):         func() jp.Packet { return &C2SChatCommandSigned{} },
		int(packets_data.C2SChatID):                      func() jp.Packet { return &C2SChat{} },
		int(packets_data.C2SChatSessionUpdateID):         func() jp.Packet { return &C2SChatSessionUpdate{} },
		int(packets_data.C2SChunkBatchReceivedID):        func() jp.Packet { return &C2SChunkBatchReceived{} },
		int(packets_data.C2SClientCommandID):             func() jp.Packet { return &C2SClientCommand{} },
		int(packets_data.C2SClientTickEndID):             func() jp.Packet { return &C2SClientTickEnd{} },
		int(packets_data.C2SClientInformationPlayID):     func() jp.Packet { return &C2SClientInformationPlay{} },
		int(packets_data.C2SCommandSuggestionID):         func() jp.Packet { return &C2SCommandSuggestion{} },
		int(packets_data.C2SConfigurationAcknowledgedID): func() jp.Packet { return &C2SConfigurationAcknowledged{} },
		int(packets_data.C2SContainerButtonClickID):      func() jp.Packet { return &C2SContainerButtonClick{} },
		int(packets_data.C2SContainerClickID):            func() jp.Packet { return &C2SContainerClick{} },
		int(packets_data.C2SContainerCloseID):            func() jp.Packet { return &C2SContainerClose{} },
		int(packets_data.C2SContainerSlotStateChangedID): func() jp.Packet { return &C2SContainerSlotStateChanged{} },
		int(packets_data.C2SCookieResponsePlayID):        func() jp.Packet { return &C2SCookieResponsePlay{} },
		int(packets_data.C2SCustomPayloadPlayID):         func() jp.Packet { return &C2SCustomPayloadPlay{} },
		int(packets_data.C2SDebugSubscriptionRequestID):  func() jp.Packet { return &C2SDebugSubscriptionRequest{} },
		int(packets_data.C2SEditBookID):                  func() jp.Packet { return &C2SEditBook{} },
		int(packets_data.C2SEntityTagQueryID):            func() jp.Packet { return &C2SEntityTagQuery{} },
		int(packets_data.C2SInteractID):                  func() jp.Packet { return &C2SInteract{} },
		int(packets_data.C2SJigsawGenerateID):            func() jp.Packet { return &C2SJigsawGenerate{} },
		int(packets_data.C2SKeepAlivePlayID):             func() jp.Packet { return &C2SKeepAlivePlay{} },
		int(packets_data.C2SLockDifficultyID):            func() jp.Packet { return &C2SLockDifficulty{} },
		int(packets_data.C2SMovePlayerPosID):             func() jp.Packet { return &C2SMovePlayerPos{} },
		int(packets_data.C2SMovePlayerPosRotID):          func() jp.Packet { return &C2SMovePlayerPosRot{} },
		int(packets_data.C2SMovePlayerRotID):             func() jp.Packet { return &C2SMovePlayerRot{} },
		int(packets_data.C2SMovePlayerStatusOnlyID):      func() jp.Packet { return &C2SMovePlayerStatusOnly{} },
		int(packets_data.C2SMoveVehicleID):               func() jp.Packet { return &C2SMoveVehicle{} },
		int(packets_data.C2SPaddleBoatID):                func() jp.Packet { return &C2SPaddleBoat{} },
		int(packets_data.C2SPickItemFromBlockID):         func() jp.Packet { return &C2SPickItemFromBlock{} },
		int(packets_data.C2SPickItemFromEntityID):        func() jp.Packet { return &C2SPickItemFromEntity{} },
		int(packets_data.C2SPingRequestPlayID):           func() jp.Packet { return &C2SPingRequestPlay{} },
		int(packets_data.C2SPlaceRecipeID):               func() jp.Packet { return &C2SPlaceRecipe{} },
		int(packets_data.C2SPlayerAbilitiesID):           func() jp.Packet { return &C2SPlayerAbilities{} },
		int(packets_data.C2SPlayerActionID):              func() jp.Packet { return &C2SPlayerAction{} },
		int(packets_data.C2SPlayerCommandID):             func() jp.Packet { return &C2SPlayerCommand{} },
		int(packets_data.C2SPlayerInputID):               func() jp.Packet { return &C2SPlayerInput{} },
		int(packets_data.C2SPlayerLoadedID):              func() jp.Packet { return &C2SPlayerLoaded{} },
		int(packets_data.C2SPongPlayID):                  func() jp.Packet { return &C2SPongPlay{} },
		int(packets_data.C2SRecipeBookChangeSettingsID):  func() jp.Packet { return &C2SRecipeBookChangeSettings{} },
		int(packets_data.C2SRecipeBookSeenRecipeID):      func() jp.Packet { return &C2SRecipeBookSeenRecipe{} },
		int(packets_data.C2SRenameItemID):                func() jp.Packet { return &C2SRenameItem{} },
		int(packets_data.C2SResourcePackPlayID):          func() jp.Packet { return &C2SResourcePackPlay{} },
		int(packets_data.C2SSeenAdvancementsID):          func() jp.Packet { return &C2SSeenAdvancements{} },
		int(packets_data.C2SSelectTradeID):               func() jp.Packet { return &C2SSelectTrade{} },
		int(packets_data.C2SSetBeaconID):                 func() jp.Packet { return &C2SSetBeacon{} },
		int(packets_data.C2SSetCarriedItemID):            func() jp.Packet { return &C2SSetCarriedItem{} },
		int(packets_data.C2SSetCommandBlockID):           func() jp.Packet { return &C2SSetCommandBlock{} },
		int(packets_data.C2SSetCommandMinecartID):        func() jp.Packet { return &C2SSetCommandMinecart{} },
		int(packets_data.C2SSetCreativeModeSlotID):       func() jp.Packet { return &C2SSetCreativeModeSlot{} },
		int(packets_data.C2SSetJigsawBlockID):            func() jp.Packet { return &C2SSetJigsawBlock{} },
		int(packets_data.C2SSetStructureBlockID):         func() jp.Packet { return &C2SSetStructureBlock{} },
		int(packets_data.C2SSetTestBlockID):              func() jp.Packet { return &C2SSetTestBlock{} },
		int(packets_data.C2SSignUpdateID):                func() jp.Packet { return &C2SSignUpdate{} },
		int(packets_data.C2SSwingID):                     func() jp.Packet { return &C2SSwing{} },
		int(packets_data.C2STeleportToEntityID):          func() jp.Packet { return &C2STeleportToEntity{} },
		int(packets_data.C2STestInstanceBlockActionID):   func() jp.Packet { return &C2STestInstanceBlockAction{} },
		int(packets_data.C2SUseItemOnID):                 func() jp.Packet { return &C2SUseItemOn{} },
		int(packets_data.C2SUseItemID):                   func() jp.Packet { return &C2SUseItem{} },
		int(packets_data.C2SCustomClickActionPlayID):     func() jp.Packet { return &C2SCustomClickActionPlay{} },
	},
	"play_s2c": {
		int(packets_data.S2CBundleDelimiterID):          func() jp.Packet { return &S2CBundleDelimiter{} },
		int(packets_data.S2CAddEntityID):                func() jp.Packet { return &S2CAddEntity{} },
		int(packets_data.S2CAnimateID):                  func() jp.Packet { return &S2CAnimate{} },
		int(packets_data.S2CAwardStatsID):               func() jp.Packet { return &S2CAwardStats{} },
		int(packets_data.S2CBlockChangedAckID):          func() jp.Packet { return &S2CBlockChangedAck{} },
		int(packets_data.S2CBlockDestructionID):         func() jp.Packet { return &S2CBlockDestruction{} },
		int(packets_data.S2CBlockEntityDataID):          func() jp.Packet { return &S2CBlockEntityData{} },
		int(packets_data.S2CBlockEventID):               func() jp.Packet { return &S2CBlockEvent{} },
		int(packets_data.S2CBlockUpdateID):              func() jp.Packet { return &S2CBlockUpdate{} },
		int(packets_data.S2CBossEventID):                func() jp.Packet { return &S2CBossEvent{} },
		int(packets_data.S2CChangeDifficultyID):         func() jp.Packet { return &S2CChangeDifficulty{} },
		int(packets_data.S2CChunkBatchFinishedID):       func() jp.Packet { return &S2CChunkBatchFinished{} },
		int(packets_data.S2CChunkBatchStartID):          func() jp.Packet { return &S2CChunkBatchStart{} },
		int(packets_data.S2CChunksBiomesID):             func() jp.Packet { return &S2CChunksBiomes{} },
		int(packets_data.S2CClearTitlesID):              func() jp.Packet { return &S2CClearTitles{} },
		int(packets_data.S2CCommandSuggestionsID):       func() jp.Packet { return &S2CCommandSuggestions{} },
		int(packets_data.S2CCommandsID):                 func() jp.Packet { return &S2CCommands{} },
		int(packets_data.S2CContainerCloseID):           func() jp.Packet { return &S2CContainerClose{} },
		int(packets_data.S2CContainerSetContentID):      func() jp.Packet { return &S2CContainerSetContent{} },
		int(packets_data.S2CContainerSetDataID):         func() jp.Packet { return &S2CContainerSetData{} },
		int(packets_data.S2CContainerSetSlotID):         func() jp.Packet { return &S2CContainerSetSlot{} },
		int(packets_data.S2CCookieRequestPlayID):        func() jp.Packet { return &S2CCookieRequestPlay{} },
		int(packets_data.S2CCooldownID):                 func() jp.Packet { return &S2CCooldown{} },
		int(packets_data.S2CCustomChatCompletionsID):    func() jp.Packet { return &S2CCustomChatCompletions{} },
		int(packets_data.S2CCustomPayloadPlayID):        func() jp.Packet { return &S2CCustomPayloadPlay{} },
		int(packets_data.S2CDamageEventID):              func() jp.Packet { return &S2CDamageEvent{} },
		int(packets_data.S2CDebugBlockValueID):          func() jp.Packet { return &S2CDebugBlockValue{} },
		int(packets_data.S2CDebugChunkValueID):          func() jp.Packet { return &S2CDebugChunkValue{} },
		int(packets_data.S2CDebugEntityValueID):         func() jp.Packet { return &S2CDebugEntityValue{} },
		int(packets_data.S2CDebugEventID):               func() jp.Packet { return &S2CDebugEvent{} },
		int(packets_data.S2CDebugSampleID):              func() jp.Packet { return &S2CDebugSample{} },
		int(packets_data.S2CDeleteChatID):               func() jp.Packet { return &S2CDeleteChat{} },
		int(packets_data.S2CDisconnectPlayID):           func() jp.Packet { return &S2CDisconnectPlay{} },
		int(packets_data.S2CDisguisedChatID):            func() jp.Packet { return &S2CDisguisedChat{} },
		int(packets_data.S2CEntityEventID):              func() jp.Packet { return &S2CEntityEvent{} },
		int(packets_data.S2CEntityPositionSyncID):       func() jp.Packet { return &S2CEntityPositionSync{} },
		int(packets_data.S2CExplodeID):                  func() jp.Packet { return &S2CExplode{} },
		int(packets_data.S2CForgetLevelChunkID):         func() jp.Packet { return &S2CForgetLevelChunk{} },
		int(packets_data.S2CGameEventID):                func() jp.Packet { return &S2CGameEvent{} },
		int(packets_data.S2CGameTestHighlightPosID):     func() jp.Packet { return &S2CGameTestHighlightPos{} },
		int(packets_data.S2CMountScreenOpenID):          func() jp.Packet { return &S2CMountScreenOpen{} },
		int(packets_data.S2CHurtAnimationID):            func() jp.Packet { return &S2CHurtAnimation{} },
		int(packets_data.S2CInitializeBorderID):         func() jp.Packet { return &S2CInitializeBorder{} },
		int(packets_data.S2CKeepAlivePlayID):            func() jp.Packet { return &S2CKeepAlivePlay{} },
		int(packets_data.S2CLevelChunkWithLightID):      func() jp.Packet { return &S2CLevelChunkWithLight{} },
		int(packets_data.S2CLevelEventID):               func() jp.Packet { return &S2CLevelEvent{} },
		int(packets_data.S2CLevelParticlesID):           func() jp.Packet { return &S2CLevelParticles{} },
		int(packets_data.S2CLightUpdateID):              func() jp.Packet { return &S2CLightUpdate{} },
		int(packets_data.S2CLoginID):                    func() jp.Packet { return &S2CLogin{} },
		int(packets_data.S2CMapItemDataID):              func() jp.Packet { return &S2CMapItemData{} },
		int(packets_data.S2CMerchantOffersID):           func() jp.Packet { return &S2CMerchantOffers{} },
		int(packets_data.S2CMoveEntityPosID):            func() jp.Packet { return &S2CMoveEntityPos{} },
		int(packets_data.S2CMoveEntityPosRotID):         func() jp.Packet { return &S2CMoveEntityPosRot{} },
		int(packets_data.S2CMoveMinecartAlongTrackID):   func() jp.Packet { return &S2CMoveMinecartAlongTrack{} },
		int(packets_data.S2CMoveEntityRotID):            func() jp.Packet { return &S2CMoveEntityRot{} },
		int(packets_data.S2CMoveVehicleID):              func() jp.Packet { return &S2CMoveVehicle{} },
		int(packets_data.S2COpenBookID):                 func() jp.Packet { return &S2COpenBook{} },
		int(packets_data.S2COpenScreenID):               func() jp.Packet { return &S2COpenScreen{} },
		int(packets_data.S2COpenSignEditorID):           func() jp.Packet { return &S2COpenSignEditor{} },
		int(packets_data.S2CPingPlayID):                 func() jp.Packet { return &S2CPingPlay{} },
		int(packets_data.S2CPongResponsePlayID):         func() jp.Packet { return &S2CPongResponsePlay{} },
		int(packets_data.S2CPlaceGhostRecipeID):         func() jp.Packet { return &S2CPlaceGhostRecipe{} },
		int(packets_data.S2CPlayerAbilitiesID):          func() jp.Packet { return &S2CPlayerAbilities{} },
		int(packets_data.S2CPlayerChatID):               func() jp.Packet { return &S2CPlayerChat{} },
		int(packets_data.S2CPlayerCombatEndID):          func() jp.Packet { return &S2CPlayerCombatEnd{} },
		int(packets_data.S2CPlayerCombatEnterID):        func() jp.Packet { return &S2CPlayerCombatEnter{} },
		int(packets_data.S2CPlayerCombatKillID):         func() jp.Packet { return &S2CPlayerCombatKill{} },
		int(packets_data.S2CPlayerInfoRemoveID):         func() jp.Packet { return &S2CPlayerInfoRemove{} },
		int(packets_data.S2CPlayerInfoUpdateID):         func() jp.Packet { return &S2CPlayerInfoUpdate{} },
		int(packets_data.S2CPlayerLookAtID):             func() jp.Packet { return &S2CPlayerLookAt{} },
		int(packets_data.S2CPlayerPositionID):           func() jp.Packet { return &S2CPlayerPosition{} },
		int(packets_data.S2CPlayerRotationID):           func() jp.Packet { return &S2CPlayerRotation{} },
		int(packets_data.S2CRecipeBookAddID):            func() jp.Packet { return &S2CRecipeBookAdd{} },
		int(packets_data.S2CRecipeBookRemoveID):         func() jp.Packet { return &S2CRecipeBookRemove{} },
		int(packets_data.S2CRecipeBookSettingsID):       func() jp.Packet { return &S2CRecipeBookSettings{} },
		int(packets_data.S2CRemoveEntitiesID):           func() jp.Packet { return &S2CRemoveEntities{} },
		int(packets_data.S2CRemoveMobEffectID):          func() jp.Packet { return &S2CRemoveMobEffect{} },
		int(packets_data.S2CResetScoreID):               func() jp.Packet { return &S2CResetScore{} },
		int(packets_data.S2CResourcePackPopPlayID):      func() jp.Packet { return &S2CResourcePackPopPlay{} },
		int(packets_data.S2CResourcePackPushPlayID):     func() jp.Packet { return &S2CResourcePackPushPlay{} },
		int(packets_data.S2CRespawnID):                  func() jp.Packet { return &S2CRespawn{} },
		int(packets_data.S2CRotateHeadID):               func() jp.Packet { return &S2CRotateHead{} },
		int(packets_data.S2CSectionBlocksUpdateID):      func() jp.Packet { return &S2CSectionBlocksUpdate{} },
		int(packets_data.S2CSelectAdvancementsTabID):    func() jp.Packet { return &S2CSelectAdvancementsTab{} },
		int(packets_data.S2CServerDataID):               func() jp.Packet { return &S2CServerData{} },
		int(packets_data.S2CSetActionBarTextID):         func() jp.Packet { return &S2CSetActionBarText{} },
		int(packets_data.S2CSetBorderCenterID):          func() jp.Packet { return &S2CSetBorderCenter{} },
		int(packets_data.S2CSetBorderLerpSizeID):        func() jp.Packet { return &S2CSetBorderLerpSize{} },
		int(packets_data.S2CSetBorderSizeID):            func() jp.Packet { return &S2CSetBorderSize{} },
		int(packets_data.S2CSetBorderWarningDelayID):    func() jp.Packet { return &S2CSetBorderWarningDelay{} },
		int(packets_data.S2CSetBorderWarningDistanceID): func() jp.Packet { return &S2CSetBorderWarningDistance{} },
		int(packets_data.S2CSetCameraID):                func() jp.Packet { return &S2CSetCamera{} },
		int(packets_data.S2CSetChunkCacheCenterID):      func() jp.Packet { return &S2CSetChunkCacheCenter{} },
		int(packets_data.S2CSetChunkCacheRadiusID):      func() jp.Packet { return &S2CSetChunkCacheRadius{} },
		int(packets_data.S2CSetCursorItemID):            func() jp.Packet { return &S2CSetCursorItem{} },
		int(packets_data.S2CSetDefaultSpawnPositionID):  func() jp.Packet { return &S2CSetDefaultSpawnPosition{} },
		int(packets_data.S2CSetDisplayObjectiveID):      func() jp.Packet { return &S2CSetDisplayObjective{} },
		int(packets_data.S2CSetEntityDataID):            func() jp.Packet { return &S2CSetEntityData{} },
		int(packets_data.S2CSetEntityLinkID):            func() jp.Packet { return &S2CSetEntityLink{} },
		int(packets_data.S2CSetEntityMotionID):          func() jp.Packet { return &S2CSetEntityMotion{} },
		int(packets_data.S2CSetEquipmentID):             func() jp.Packet { return &S2CSetEquipment{} },
		int(packets_data.S2CSetExperienceID):            func() jp.Packet { return &S2CSetExperience{} },
		int(packets_data.S2CSetHealthID):                func() jp.Packet { return &S2CSetHealth{} },
		int(packets_data.S2CSetHeldSlotID):              func() jp.Packet { return &S2CSetHeldSlot{} },
		int(packets_data.S2CSetObjectiveID):             func() jp.Packet { return &S2CSetObjective{} },
		int(packets_data.S2CSetPassengersID):            func() jp.Packet { return &S2CSetPassengers{} },
		int(packets_data.S2CSetPlayerInventoryID):       func() jp.Packet { return &S2CSetPlayerInventory{} },
		int(packets_data.S2CSetPlayerTeamID):            func() jp.Packet { return &S2CSetPlayerTeam{} },
		int(packets_data.S2CSetScoreID):                 func() jp.Packet { return &S2CSetScore{} },
		int(packets_data.S2CSetSimulationDistanceID):    func() jp.Packet { return &S2CSetSimulationDistance{} },
		int(packets_data.S2CSetSubtitleTextID):          func() jp.Packet { return &S2CSetSubtitleText{} },
		int(packets_data.S2CSetTimeID):                  func() jp.Packet { return &S2CSetTime{} },
		int(packets_data.S2CSetTitleTextID):             func() jp.Packet { return &S2CSetTitleText{} },
		int(packets_data.S2CSetTitlesAnimationID):       func() jp.Packet { return &S2CSetTitlesAnimation{} },
		int(packets_data.S2CSoundEntityID):              func() jp.Packet { return &S2CSoundEntity{} },
		int(packets_data.S2CSoundID):                    func() jp.Packet { return &S2CSound{} },
		int(packets_data.S2CStartConfigurationID):       func() jp.Packet { return &S2CStartConfiguration{} },
		int(packets_data.S2CStopSoundID):                func() jp.Packet { return &S2CStopSound{} },
		int(packets_data.S2CStoreCookiePlayID):          func() jp.Packet { return &S2CStoreCookiePlay{} },
		int(packets_data.S2CSystemChatID):               func() jp.Packet { return &S2CSystemChat{} },
		int(packets_data.S2CTabListID):                  func() jp.Packet { return &S2CTabList{} },
		int(packets_data.S2CTagQueryID):                 func() jp.Packet { return &S2CTagQuery{} },
		int(packets_data.S2CTakeItemEntityID):           func() jp.Packet { return &S2CTakeItemEntity{} },
		int(packets_data.S2CTeleportEntityID):           func() jp.Packet { return &S2CTeleportEntity{} },
		int(packets_data.S2CTestInstanceBlockStatusID):  func() jp.Packet { return &S2CTestInstanceBlockStatus{} },
		int(packets_data.S2CTickingStateID):             func() jp.Packet { return &S2CTickingState{} },
		int(packets_data.S2CTickingStepID):              func() jp.Packet { return &S2CTickingStep{} },
		int(packets_data.S2CTransferPlayID):             func() jp.Packet { return &S2CTransferPlay{} },
		int(packets_data.S2CUpdateAdvancementsID):       func() jp.Packet { return &S2CUpdateAdvancements{} },
		int(packets_data.S2CUpdateAttributesID):         func() jp.Packet { return &S2CUpdateAttributes{} },
		int(packets_data.S2CUpdateMobEffectID):          func() jp.Packet { return &S2CUpdateMobEffect{} },
		int(packets_data.S2CUpdateRecipesID):            func() jp.Packet { return &S2CUpdateRecipes{} },
		int(packets_data.S2CUpdateTagsPlayID):           func() jp.Packet { return &S2CUpdateTagsPlay{} },
		int(packets_data.S2CProjectilePowerID):          func() jp.Packet { return &S2CProjectilePower{} },
		int(packets_data.S2CCustomReportDetailsPlayID):  func() jp.Packet { return &S2CCustomReportDetailsPlay{} },
		int(packets_data.S2CServerLinksPlayID):          func() jp.Packet { return &S2CServerLinksPlay{} },
		int(packets_data.S2CWaypointID):                 func() jp.Packet { return &S2CWaypoint{} },
		int(packets_data.S2CClearDialogPlayID):          func() jp.Packet { return &S2CClearDialogPlay{} },
		int(packets_data.S2CShowDialogPlayID):           func() jp.Packet { return &S2CShowDialogPlay{} },
	},
}
